name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Read release info from file
        id: release-info
        run: |
          echo "::set-output name=tag::$(grep -oP '(?<=versionName ").*(?=")' app/buil.gradle)"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Git Tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a ${{ steps.release-info.outputs.tag }} -m "Release v${{ steps.release-info.outputs.tag }}"
          git push --tags --verbose
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-info.outputs.tag }}
          release_name: ${{ steps.release-info.outputs.tag }}
          body: Release notes
