name: Android Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 #https://github.com/actions/checkout 
        with:
          ref: main #branch name
          
      - name: Print files list
        run: |
          echo "The value of tag is grep : $(ls -R -maxdepth 5)"
