name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read release info from files
        id: release-info
        run: |
          echo "The value of tag is grep : $(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)"
          echo "tag=$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)" >> $GITHUB_OUTPUT
      - name: Create Git Tag
        run: |
          tag=v$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a v${tag} -m "Release v${tag}"
          git push origin tag --verbose




