name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: List directory contents
        run: ls -R $HOME
      - name: Read release info from files
        id: release-info
        run: |
          echo "The value of tag is: $(awk -F'\"' '/versionName/{print $2}' $HOME/work/CodeCoverageApp/app/build.gradle)"
