name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Read release info from files
        id: release-info
        run: |
          echo "::set-output name=tag::$(awk -F'\"' '/versionName/{print $2}' ../../app/build.gradle)"


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Git Tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a v${{ steps.release-info.outputs.tag }} -m "Release -v${{ steps.release-info.outputs.tag }}"
          git push --tags --verbose
