name: Android Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # - https://github.com/actions/checkout
        with:
          ref: main #branch name
      
      - name: Create tag from versonName
        id: create-tag
        run: |
          echo "tag=v$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)" >> $GITHUB_OUTPUT
          
          
      - name: Check Tag Existence
        id: check_tag
        run: |
          TAG_NAME=${{steps.create-tag.outputs.tag}}
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${TAG_NAME}")
          if [[ "$RESPONSE" == "200" ]]; then
            echo "::set-output name=tag_exists::true"
            echo "Tag ${TAG_NAME} - exists  yes"
          else
            echo "::set-output name=tag_exists::false"
            echo "Tag ${TAG_NAME} - exists  false"
          fi
          
          
      - name: Print tag existance
        run: |
          tag=${{steps.create-tag.outputs.tag}}
          tag_exists=${{steps.create-tag.outputs.tag_exists}}
          echo "Tag ${tag} - exists == steps.create-tag.outputs.tag_exists"
          


