name: Android Release dev

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 #https://github.com/actions/checkout 
        with:
          ref: main #branch name
      - name: Print files list
        run: |
          echo "The value of tag is grep : $(grep -oP '(?<=versionName =").*(?=")' SwapcardProject/build.gradle.kts)"
      - name: Create tag from versonName
        id: create-tag
        run: |
          versionName=$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)
          echo "tag=v${versionName}" >> $GITHUB_OUTPUT
          
      - name: Check Tag Existence hmm
        id: check_tag
        run: |
          TAG_NAME=${{steps.create-tag.outputs.tag}}
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${TAG_NAME}")
          if [[ "$RESPONSE" == "200" ]]; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Git Tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          tag=${{steps.create-tag.outputs.tag}}
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a ${tag} -m "Release ${tag}"
          git push origin $tag --verbose

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1 #https://github.com/ncipollo/release-action 
        with:
          tag: ${{ steps.create-tag.outputs.tag }}
          name: Release ${{ steps.create-tag.outputs.tag }}
          bodyFile: changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
          skipIfReleaseExists: true
          draft: true
          


