name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read release info from files
        id: release-info
        run: |
          echo "The value of tag is grep : $(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)"
          echo "::set-output name=tag::$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)"
          echo "::set-output name=notes::$(cat changelog.md)"
          echo "changelog=$(cat changelog.md)" >> $GITHUB_OUTPUT
          echo "The change log : $(cat changelog.md)"
          echo "The change log for new ====> : ${{ steps.release-info.outputs.changelog }}"




