name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get git tag
        id: create-tag
        run: |
          echo "The value of tag is grep : $(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)"
          echo "tag=v$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)" >> $GITHUB_OUTPUT
          
      - name: Create Git Tag
        run: |
          tag=${{steps.create-tag.outputs.tag}}
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a ${tag} -m "Release ${tag}"
          git push origin $tag --verbose
          
      - name: Read changelog.md
        id: read-changelog
        run: |
          changelog=$(cat changelog.md)
          #echo "::set-output name=changelog::$changelog"
          echo "::set-output name=changelog::$(cat changelog.md)"


      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create-tag.outputs.tag }}
          release_name: Release ${{ steps.create-tag.outputs.tag }}
          body: |
            ${{ steps.read-changelog.outputs.changelog }}
          #body: ${{ steps.read-changelog.outputs.changelog }}
          


