name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read release info from files
        id: release-info
        run: |
          echo "The value of tag is grep : $(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)"
          echo "tag=$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)" >> $GITHUB_OUTPUT
          echo CHANGE_LOG=$(cat changelog.md)" >> $GITHUB_OUTPUT
      - name: Print values
        id: print-values
        run: |
          echo "The tag for new ====> : ${env.tag }"
          echo "The change log ====> : ${ env.CHANGE_LOG }"




