name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read release info from files
        id: release-info
        run: |
          echo "The value of tag is awk : $(awk -F'\"' '/versionName/{print $2}' app/build.gradle)"
          echo "The value of tag is grep : $(grep -oP '(?<=versionName ").*(?=")' app/buil.gradle)"


