name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create git tag
        id: create-tag
        run: |
          echo "The value of tag is grep : $(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)"
          echo "tag=v$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)" >> $GITHUB_OUTPUT
      - name: Create Git Tag
        run: |
          tag=${{steps.create-tag.outputs.tag}}
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a ${tag} -m "Release ${tag}"
          git push origin $tag --verbose




