name: Releases on Tag push

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # - https://github.com/actions/checkout
        with:
          ref: main #branch name
          
      - name: Create tag from versonName
        id: create-tag
        run: |
          echo "tag=v$(grep -oP '(?<=versionName ").*(?=")' app/build.gradle)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1 #https://github.com/ncipollo/release-action
        with:
          tag: ${{ steps.create-tag.outputs.tag }}
          name: Release ${{ steps.create-tag.outputs.tag }}
          bodyFile: changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
          skipIfReleaseExists: true
